name: CI/CD for Django Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSh_HOST }}
        SSH_PORT: 22
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -P $SSH_PORT deploy_script.sh $SSH_USER@$SSH_HOST:/tmp/deploy_script.sh
        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST 'bash /tmp/deploy_script.sh'
        rm private_key
